/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Moderatore;

/**
 *
 * @author davidepetrini
 */
public class ModeratoreView extends javax.swing.JPanel {

    /**
     * Creates new form ModeratoreView
     */
    public ModeratoreView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnProfPers = new javax.swing.JButton();
        btnProfGaming = new javax.swing.JButton();
        btnVaiGiochi = new javax.swing.JButton();
        btnListaUtenti = new javax.swing.JButton();
        btnListaRecens = new javax.swing.JButton();
        btnEsci = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel1.setText("Benvenuto <dinamic> [M]");

        btnProfPers.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnProfPers.setText("Profilo Personale");

        btnProfGaming.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnProfGaming.setText("Profilo Gaming");
        btnProfGaming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfGamingActionPerformed(evt);
            }
        });

        btnVaiGiochi.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnVaiGiochi.setText("Vai ai Giochi");
        btnVaiGiochi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaiGiochiActionPerformed(evt);
            }
        });

        btnListaUtenti.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnListaUtenti.setText("Lista Utenti");
        btnListaUtenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaUtentiActionPerformed(evt);
            }
        });

        btnListaRecens.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnListaRecens.setText("Lista recensioni");
        btnListaRecens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaRecensActionPerformed(evt);
            }
        });

        btnEsci.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnEsci.setText("Esci");
        btnEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnProfGaming, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListaRecens, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnProfPers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVaiGiochi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(btnEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnListaUtenti, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListaUtenti)
                    .addComponent(btnProfPers))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListaRecens)
                    .addComponent(btnProfGaming))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEsci)
                    .addComponent(btnVaiGiochi))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfGamingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfGamingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfGamingActionPerformed

    private void btnVaiGiochiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaiGiochiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVaiGiochiActionPerformed

    private void btnListaUtentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaUtentiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaUtentiActionPerformed

    private void btnListaRecensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaRecensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaRecensActionPerformed

    private void btnEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEsciActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsci;
    private javax.swing.JButton btnListaRecens;
    private javax.swing.JButton btnListaUtenti;
    private javax.swing.JButton btnProfGaming;
    private javax.swing.JButton btnProfPers;
    private javax.swing.JButton btnVaiGiochi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
